spring:
  application:
    name: ${SPRING_APPLICATION_NAME:SOM}

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}

server:
  port: ${PORT:8080}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}
  enabled: ${DISCORD_WEBHOOK_ENABLED:true}
  environment: ${DISCORD_ENVIRONMENT}